---
- name: SUPERSET | Install
  import_tasks: install.yml
  tags:
    - superset_install

- name: SUPERSET | Install Firefox and geckodriver
  import_tasks: install-firefox.yml
  tags:
    - superset_firefox
  when: superset_webdriver_type == "firefox"

- name: SUPERSET | Install Chrome and chromeDriver
  import_tasks: install-chrome.yml
  tags:
    - superset_chrome
  when: superset_webdriver_type == "chrome"

- name: SUPERSET | Configure
  import_tasks: config.yml
  tags:
    - superset_configure

- name: SUPERSET | Scripts
  import_tasks: scripts.yml
  tags:
    - superset_scripts

- name: SUPERSET | Service
  import_tasks: service.yml
  tags:
    - superset_service
