---

- name: SUPERSET | Copy Daemon script
  template:
    src: "{{ superset_service_template_path }}"
    dest: "/etc/systemd/system/{{ superset_service_name }}.service"
    mode: 0644
    owner: root
    group: root

- name: SUPERSET | Configuring service
  systemd:
    name: "{{ superset_service_name }}"
    state: "{{ superset_service_state }}"
    enabled: "{{ superset_service_enabled }}"
    daemon_reload: yes

- name: SUPERSET | Wait for service health OK
  uri:
    url: "{{ superset_health_url }}"
    status_code: 200
  retries: "{{ superset_check_wait_num_retries }}"
  delay: "{{ superset_check_start_delay }}"
  register: result
  until: result.status in [200]
  changed_when: false
  when:
    - superset_service_state == 'started'
